---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: ci
  pull: default
  image: rancherlabs/rke:latest
  commands:
  - mage build
  - ls -lR build/bin
  environment:
    CROSS: 1
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: stage-binaries
  pull: default
  image: rancherlabs/rke:latest
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*"

- name: github_binary_prerelease
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "build/bin/rke*"
    prerelease: true
    title: "Pre-release ${DRONE_TAG}"
    note: ./build/bin/rke-k8sversions.txt
    overwrite: true
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    checksum:
    - sha256
    files:
    - "build/bin/rke*"
    api_key:
      from_secret: github_token
    title: "Release ${DRONE_TAG}"
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: dispatch
  image: curlimages/curl:7.81.0
  user: root
  environment:
    PAT_USERNAME:
      from_secret: pat_username
    PAT_TOKEN:
      from_secret: github_token
  commands:
  - apk -U --no-cache add bash
  - scripts/dispatch
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: test-cni

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancherlabs/rke:latest
  commands:
  - mage build
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: integration-flannel
  pull: default
  image: rancherlabs/rke:latest
  commands:
  - scripts/integration flannel
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: integration-calico
  pull: default
  image: rancherlabs/rke:latest
  commands:
  - scripts/integration calico
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: integration-weave
  pull: default
  image: rancherlabs/rke:latest
  commands:
  - scripts/integration weave
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    when:
      instance:
        - drone-publish.rancher.io
