---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: ci
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  - ls -lR dist/artifacts
  environment:
    CROSS: 1
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock


- name: stage-binaries
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*"

- name: github_binary_prerelease
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "build/bin/rke_*"
    - "dist/artifacts/${DRONE_TAG}/*"
    prerelease: true
    title: "Pre-release ${DRONE_TAG}"
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    checksum:
    - sha256
    files:
    - "build/bin/rke_*"
    - "dist/artifacts/${DRONE_TAG}/*"
    api_key:
      from_secret: github_token
    title: "Release ${DRONE_TAG}"
  when:
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: test-cni

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper build
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: integration-flannel
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper integration flannel
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: integration-calico
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper integration calico
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: integration-weave
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper integration weave
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
